# Generated by Django 5.0.2 on 2025-06-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Departman Adı')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ürün Adı')),
                ('minimum_quantity', models.IntegerField(default=0, verbose_name='Minimum Miktar')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Kalan Stok')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Miktar Türü')),
            ],
            options={
                'verbose_name': 'Miktar Türü',
                'verbose_name_plural': 'Miktar Türleri',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Raf Numarası')),
            ],
            options={
                'verbose_name': 'Raf',
                'verbose_name_plural': 'Raflar',
            },
        ),
        migrations.CreateModel(
            name='ExitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField(auto_now_add=True, verbose_name='Çıkış Tarihi')),
                ('quantity', models.IntegerField(verbose_name='Çıkış Miktarı')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depo.department', verbose_name='Çıkış Departmanı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Çıkış Hareketi',
                'verbose_name_plural': 'Ürün Çıkış Hareketleri',
            },
        ),
        migrations.CreateModel(
            name='EntryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Giriş Tarihi')),
                ('quantity', models.IntegerField(verbose_name='Giriş Miktarı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Giriş Hareketi',
                'verbose_name_plural': 'Ürün Giriş Hareketleri',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depo.quantitytype', verbose_name='Miktar Türü'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depo.shelf', verbose_name='Raf Numarası'),
        ),
    ]
