# Generated by Django 5.0.2 on 2025-06-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrytransaction',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AddField(
            model_name='entrytransaction',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_transactions', to='depo.shelf'),
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_transactions', to='depo.product'),
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
