# Generated by Django 5.0.2 on 2025-06-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0002_alter_entrytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrytransaction',
            options={'verbose_name': 'Ürün Giriş Hareketi', 'verbose_name_plural': 'Ürün Giriş Hareketleri'},
        ),
        migrations.RemoveField(
            model_name='entrytransaction',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depo.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='entrytransaction',
            name='quantity',
            field=models.IntegerField(verbose_name='Giriş Miktarı'),
        ),
    ]
